/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'Patryk' at '6/20/17 6:22 AM' with Gradle 3.0
 *
 * @author Patryk, @date 6/20/17 6:22 AM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
